EDGCSOFT-39: Spring Boot 2.7 for Morning Glory R2 2022
folio-org/edge-caiasoft pull request #25
Opened 2022-06-01 13:17 UTC by IlliaDaliek

Jira: https://issues.folio.org/browse/EDGCSOFT-39

### PURPOSE
Update the Spring Boot to 2.7.0

2022-06-03 13:32 UTC, alekGbuz approved these changes

2022-06-03 14:18 UTC, siarhei-charniak approved these changes

2022-06-05 10:47 UTC, julianladisch approved these changes

2022-06-05 11:10 UTC, julianladisch requested changes
Please do not downgrade log4j2 from 2.17.2 to 2.17.0.

Please remove <log4j2.version>2.17.0</log4j2.version> from pom.xml: https://github.com/folio-org/edge-caiasoft/pull/25/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8R33

spring-boot-starter-parent 2.7.0 includes spring-boot-dependencies 2.7.0 that sets log4j2.version to 2.17.2:
https://github.com/spring-projects/spring-boot/blob/v2.7.0/spring-boot-project/spring-boot-dependencies/build.gradle#L1128

2022-06-06 11:01 UTC, merged

2022-06-07 12:40 UTC, julianladisch reviewed
Looks good, thanks!